spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingdb
    username: root
    password: Uday@778
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084
